;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        go-mode-insert-and-indent
        helm-for-files
        ido-switch-project
        indent-for-tab-command
        kill-line-and-one-space
        mark-sexp
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-forward-sentence
        org-self-insert-command
        org-shiftright
        sh-assignment
        smarter-move-beginning-of-line
        wdired-finish-edit
        wdired-previous-line
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-pound
        helm-show-kill-ring
        ido-open-file
        mouse-drag-mode-line
        mouse-set-region
        org-cycle
        search-string-in-project-dir
        ))
