;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mark-sexp
        mouse-minor-mode-menu
        org-delete-backward-char
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-backspace
        end-of-buffer
        js3-mode-show-node
        mc/create-fake-cursor-at-point
        mouse-appearance-menu
        next-buffer
        org-self-insert-command
        previous-buffer
        mc/add-cursor-on-click
        ))
