(package-initialize)
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)

(load "~/.emacs.d/etc/functions.el")(get-time "functions.el")
(timed-load "~/.emacs.d/etc/packages.el")
(timed-load "~/.emacs.d/etc/setup.el")
(timed-load "~/.emacs.d/etc/keys.el")
(timed-load "~/.emacs.d/etc/projects.el")
(timed-load "~/.emacs.d/etc/hooks.el")
(timed-load "~/.emacs.d/etc/custom.el")
