(load "~/.emacs.d/config/timer")

(load "~/.emacs.d/config/paths")
(get-time)
(load "~/.emacs.d/config/base")
(get-time)
(load "~/.emacs.d/config/ui")
(get-time)
(load "~/.emacs.d/config/term")
(get-time)
(load "~/.emacs.d/config/indent")
(get-time)
(load "~/.emacs.d/config/common")
(get-time)
(load "~/.emacs.d/config/hooks")
(get-time)
(load "~/.emacs.d/config/modes")
(get-time)
(load "~/.emacs.d/config/functions")
(get-time)
(load "~/.emacs.d/config/keys")
(get-time)
(load "~/.emacs.d/config/text")
(get-time)

;; Misc
(load "~/.emacs.d/config/hacks")
(get-time)
(load "~/.emacs.d/config/macros")
(get-time)
(load "~/.emacs.d/config/modeline")
(get-time)
(load "~/.emacs.d/config/projects")
(get-time)
(load "~/.emacs.d/config/regexp")
(get-time)
(load "~/.emacs.d/config/server")
(get-time)
;; (load "~/.emacs.d/config/webjump")
;; (get-time)
(load "~/.emacs.d/config/ac")
(get-time)
(load "~/.emacs.d/config/custom")
(get-time)
;; (load "~/.emacs.d/config/elnode")
;; (get-time)
(load "~/.emacs.d/config/generic")
(get-time)
(load "~/.emacs.d/config/global")
(get-time)
;; (load "~/.emacs.d/config/gnus")
;; (get-time)
(load "~/.emacs.d/config/machine")
(get-time)
;; Communication


(load "~/.emacs.d/config/org")
(get-time)

;; Programming
(load "~/.emacs.d/config/vcs")
(get-time)
(load "~/.emacs.d/config/shell")
(get-time)
(load "~/.emacs.d/config/bdd")
(get-time)
(load "~/.emacs.d/config/elisp")
(get-time)
(load "~/.emacs.d/config/go")
(get-time)
(load "~/.emacs.d/config/javascript")
(get-time)
(load "~/.emacs.d/config/php")
(get-time)
(load "~/.emacs.d/config/ruby")
(get-time)
(load "~/.emacs.d/config/sql")
(get-time)
(load "~/.emacs.d/config/symfony2")
(get-time)
(load "~/.emacs.d/config/nodejs")
(get-time)
(load "~/.emacs.d/config/web")
(get-time)
(load "~/.emacs.d/config/xml")
(get-time)
