(load "~/.emacs.d/config/paths.el")
(load "~/.emacs.d/config/base.el")
(load "~/.emacs.d/config/ui.el")
(load "~/.emacs.d/config/term.el")
(load "~/.emacs.d/config/indent.el")
(load "~/.emacs.d/config/common.el")
(load "~/.emacs.d/config/hooks.el")
(load "~/.emacs.d/config/modes.el")


(load "~/.emacs.d/config/hacks.el")
(load "~/.emacs.d/config/keys.el")
(load "~/.emacs.d/config/macros.el")
(load "~/.emacs.d/config/modeline.el")
(load "~/.emacs.d/config/projects.el")
(load "~/.emacs.d/config/regexp.el")
(load "~/.emacs.d/config/server.el")
(load "~/.emacs.d/config/webjump.el")
(load "~/.emacs.d/config/ac.el")
(load "~/.emacs.d/config/custom.el")
(load "~/.emacs.d/config/elnode.el")
(load "~/.emacs.d/config/erc.el")
(load "~/.emacs.d/config/twitter.el")
(load "~/.emacs.d/config/functions.el")
(load "~/.emacs.d/config/generic.el")
(load "~/.emacs.d/config/global.el")
(load "~/.emacs.d/config/gnus.el")

(load "~/.emacs.d/config/org.el")
(load "~/.emacs.d/config/vcs.el")

(load "~/.emacs.d/config/shell.el")
(load "~/.emacs.d/config/bdd.el")
(load "~/.emacs.d/config/elisp.el")
(load "~/.emacs.d/config/go.el")
(load "~/.emacs.d/config/javascript.el")
(load "~/.emacs.d/config/php.el")
(load "~/.emacs.d/config/ruby.el")
(load "~/.emacs.d/config/sql.el")
(load "~/.emacs.d/config/symfony2.el")
(load "~/.emacs.d/config/nodejs.el")
(load "~/.emacs.d/config/web.el")
(load "~/.emacs.d/config/xml.el")
