(setq emacs-dir "~/.emacs.d")

(load (concat emacs-dir "/config/base.el"))
(load (concat emacs-dir "/config/autoload.el"))
(load (concat emacs-dir "/config/functions.el"))
(load (concat emacs-dir "/config/projects.el"))
(load (concat emacs-dir "/config/keys.el"))
(load (concat emacs-dir "/config/machine.el"))
(load (concat emacs-dir "/config/custom.el"))
(load (concat emacs-dir "/config/prog.el"))
