* Jacek Wysocki Emacs configs

My recently updated emacs confg files. Why not one of predefined config suite?
Because this one is better: is written for my needs, is almost twice faster than 
prelude (I'm not loading unnecessary files)


** Installation

Clone repository in your $HOME

#+BEGIN_SRC sh
git clone git@github.com:exu/emacs.d.git
# ensure that there is no emacs.d
mv ~/.emacs.d/ .emacs.d.backup
mv emacs.d ~/.emacs.d
#+END_SRC


After cloning repo you should run

#+BEGIN_SRC sh
cd ~/.emacs.d
./vendors reinstall
#+END_SRC

** If you want to update all git-based vendors you should run 

#+BEGIN_SRC sh
cd ~/.emacs.d
./vendors update
#+END_SRC

* How does it work?
I've split my configuration files in different folders.

** Folders

*** autoload
I've implemented autoloading like in "Prelude" project, 
every file that you put into this folder will be auto-loaded
You can remove all my files and put your own.


*** config
In this directory are all files that are loaded manually in `init.el` 
file. When you need to load files in specific order this folder is 
good to do it. You should load these file `(load "config/filename.el")`
manually in init.el file.

*** vendor
All libraries from git, installed from vendors bash script

*** machine
Machine based files, if you have emacs on different compouters you 
can easily manage machine specific config in every of these files.

*** bookmarks 
bookmarks are machine depenedent too

*** var
variable files tmp files
