#!/usr/bin/env bash

VENDORS=(
#git submodule add for each to vendor

# Shell related tools
git@github.com:dimitri/cssh.git

# Language modes
git@github.com:nablaone/slime.git
git@github.com:Gozala/slime-js.git

git@github.com:joshwnj/json-mode.git
git@github.com:yoshiki/yaml-mode.git

git@github.com:defunkt/coffee-mode.git
git@github.com:brianc/jade-mode.git
git@github.com:purcell/less-css-mode.git

git@github.com:thomblake/js3-mode.git
git@github.com:abicky/nodejs-mode.el.git
git@github.com:ejmr/php-mode.git
git@github.com:fxbois/web-mode.git

git@github.com:defunkt/markdown-mode.git


# git@github.com:technomancy/rinari.git - i'm coding in rails by now

# Testing
git@github.com:michaelklishin/cucumber.el.git

# Enhanced code writing
git@github.com:magnars/expand-region.el.git
git@github.com:magnars/multiple-cursors.el.git
git@github.com:auto-complete/auto-complete.git
git@github.com:capitaomorte/yasnippet.git
git@github.com:rooney/zencoding.git

# Better Emacs UI
git@github.com:dimitri/switch-window.git
git@github.com:emacs-helm/helm.git
git@github.com:emacsmirror/rainbow-mode.git
git@github.com:jlr/rainbow-delimiters.git
#git@github.com:tlh/workgroups.el.git

# Parsing and compiling code
git@github.com:illusori/emacs-flymake.git
git@github.com:illusori/emacs-flymake-cursor.git
git@github.com:illusori/emacs-flymake-phpcs.git
git@github.com:emacsmirror/etags-select.git

# Debugging and profiling
git@github.com:emacsattic/geben.git

# Git and guthub integration
git@github.com:sigma/gh.el.git
git@github.com:defunkt/gist.el.git
git@github.com:magit/magit.git

# Communication tools
git@github.com:hayamiz/twittering-mode.git

# Other libraries dependencies
git@github.com:sigma/logito.git
git@github.com:sigma/pcache.git
git@github.com:auto-complete/popup-el.git
git@github.com:magnars/dash.el.git
git@github.com:magnars/s.el.git


# Org-mode libraries
git@github.com:alexhenning/ORGMODE-Markdown.git

# Spelling
git@github.com:manzyuk/google-translate.git

# TODO: Migration from elpa packages
git@github.com:capitaomorte/autopair.git
git@github.com:jhelwig/ack-and-a-half.git
git@github.com:purcell/exec-path-from-shell.git

# TODO: To check in free time
 # git@github.com:kingtim/nrepl.el.git # find way to integrate php js and others
 # git@github.com:bbatsov/projectile.git
 # git@github.com:mgallego/sf.el.git
 # git@github.com:hvesalai/scala-mode2.git
 # git@github.com:smtlaissezfaire/erlang_mode.git
)


function default {
    echo "Usage:"
    echo "--------------------------------------------------------------------------------"
    echo "./vendors [reinstall|update]"
}

function reinstall {
    for vendor in "${VENDORS[@]}"
    do
        cd ~/.emacs.d/
        name="${vendor#*/}"
        name="${name/.git/}" #i didn't find how to make it in one command
        destination="./vendor/${name}"
        if [ -d "$destination" ]; then
            rm -rf $destination
        fi
        git clone --depth=1 $vendor $destination
    done

    curl -L http://mumble.net/~campbell/emacs/paredit.el > ~/.emacs.d/vendor/paredit.el
}



function update {
    for vendor in "${VENDORS[@]}"
    do
        cd ~/.emacs.d/
        name="${vendor#*/}"
        name="${name/.git/}" #i didn't find how to make it in one command
        destination="vendor/${name}"
        cd $destination
        git pull --depth=1
    done

    cd ~/.emacs.d/
}

case "$1" in
    "reinstall") reinstall ;;
    "update") update ;;
    *) default ;;
esac
