#!/usr/bin/env bash

VENDORS=(
# Shell related tools
git@github.com:dimitri/cssh.git

# Language modes
git@github.com:nablaone/slime.git
git@github.com:Gozala/slime-js.git

git@github.com:joshwnj/json-mode.git
git@github.com:yoshiki/yaml-mode.git

git@github.com:defunkt/coffee-mode.git
git@github.com:syohex/emacs-sourcemap.git
git@github.com:brianc/jade-mode.git
git@github.com:purcell/less-css-mode.git

git@github.com:skeeto/emacs-http-server.git
git@github.com:mooz/js2-mode.git
git@github.com:skeeto/skewer-mode.git
git@github.com:netguy204/imp.el.git

git@github.com:abicky/nodejs-mode.el.git
git@github.com:ejmr/php-mode.git
git@github.com:fxbois/web-mode.git
git@github.com:magnars/angular-snippets.el.git

git@github.com:defunkt/markdown-mode.git
git@github.com:kinjo/org-impress-js.el.git
git@github.com:puppetlabs/puppet-syntax-emacs.git
git@github.com:ppareit/graphviz-dot-mode.git
git@github.com:spotify/dockerfile-mode.git

# Testing
git@github.com:michaelklishin/cucumber.el.git

# Enhanced code writing
git@github.com:magnars/expand-region.el.git
git@github.com:magnars/multiple-cursors.el.git
git@github.com:auto-complete/auto-complete.git
git@github.com:capitaomorte/yasnippet.git
git@github.com:rooney/zencoding.git

# Better Emacs UI
git@github.com:bbatsov/projectile.git
git@github.com:dimitri/switch-window.git
git@github.com:emacs-helm/helm.git
git@github.com:emacsmirror/rainbow-mode.git
git@github.com:jlr/rainbow-delimiters.git
git@github.com:benma/visual-regexp.el.git
git@github.com:benma/visual-regexp-steroids.el.git #python regexp backend
git@https://github.com/Wilfred/ag.el # ag - https://github.com/ggreer/the_silver_searcher integration
#git@github.com:tlh/workgroups.el.git


# Parsing and compiling code
git@github.com:illusori/emacs-flymake.git
git@github.com:illusori/emacs-flymake-cursor.git
git@github.com:illusori/emacs-flymake-phpcs.git
git@github.com:emacsmirror/etags-select.git
git@github.com:Wilfred/flymake-jshint.el.git

# Debugging and profiling
# git@github.com:emacsattic/geben.git # from elpa works
git@github.com:tkf/emacs-request.git
git@github.com:pashky/restclient.el.git

# Git and guthub integration
git@github.com:sigma/gh.el.git
git@github.com:defunkt/gist.el.git

git@github.com:magit/magit.git
git@github.com:magit/git-modes.git

# Communication tools
git@github.com:hayamiz/twittering-mode.git
# git@github.com:skeeto/elfeed.git
git://git.savannah.nongnu.org/bbdb.git

# Other libraries dependencies
git@github.com:sigma/logito.git
git@github.com:sigma/pcache.git
git@github.com:auto-complete/popup-el.git
git@github.com:magnars/dash.el.git
git@github.com:magnars/s.el.git

# Speling
# git@github.com:manzyuk/google-translate.git

# TODO: Migration from elpa packages
git@github.com:capitaomorte/autopair.git
git@github.com:jhelwig/ack-and-a-half.git
git@github.com:purcell/exec-path-from-shell.git

# Tools
git@github.com:m00natic/vlfi.git

# TODO: To check in free time
# git@github.com:kingtim/nrepl.el.git # find way to integrate php js and others
# git@github.com:mgallego/sf.el.git
# git@github.com:hvesalai/scala-mode2.git
# git@github.com:smtlaissezfaire/erlang_mode.git
)


function default {
    echo "Usage:"
    echo "--------------------------------------------------------------------------------"
    echo "./vendors [reinstall|update|recompile]"
}

function reinstall {
    for vendor in "${VENDORS[@]}"
    do
        cd ~/.emacs.d/
        name="${vendor#*/}"
        name="${name/.git/}" #i didn't find how to make it in one command
        destination="./vendor/${name}"
        if [ -d "$destination" ]; then
            rm -rf $destination
        fi
        git clone --depth=1 $vendor $destination
    done

    #single files
    rm -rf ~/.emacs.d/vendor/go-mode/ && mkdir ~/.emacs.d/vendor/go-mode/
    curl -L 'http://golang.org/misc/emacs/go-mode-load.el?m=text' > ~/.emacs.d/vendor/go-mode/go-mode-load.el
    curl -L 'http://golang.org/misc/emacs/go-mode.el?m=text' > ~/.emacs.d/vendor/go-mode/go-mode.el

    curl -L 'http://mumble.net/~campbell/emacs/paredit.el' > ~/.emacs.d/vendor/paredit.el
    curl -L 'http://fly.srk.fer.hr/~hniksic/emacs/htmlize.el.cgi' > ~/.emacs.d/vendor/htmlize.el
    curl -L 'http://www.northbound-train.com/emacs/whole-line-or-region.el' > ~/.emacs.d/vendor/whole-line-or-region.el
    curl -L 'https://raw.github.com/alk/gpicker/master/gpicker.el' > ~/.emacs.d/vendor/gpicker.el
    curl -L 'https://raw.github.com/nsf/gocode/master/emacs/go-autocomplete.el' > ~/.emacs.d/vendor/go-autocomplete.el

    #Geben from google code sources
    mkdir -p ~/tmp/
    curl -L https://geben-on-emacs.googlecode.com/files/geben-0.26.tar.gz > ~/tmp/geben.tar.gz
    tar zxf ~/tmp/geben.tar.gz -C ~/tmp/
    cd ~/tmp/geben-0.26
    make
    SITELISP=$HOME/.emacs.d/vendor/ make install
    cd -


}

function recompile {
    emacs --batch -f batch-byte-compile ~/.emacs.d/vendor/js3-mode/js3.el
    emacs --batch -f batch-byte-compile ~/.emacs.d/vendor/js3-mode/js3-mode.el
}

function update {
    for vendor in "${VENDORS[@]}"
    do
        cd ~/.emacs.d/
        name="${vendor#*/}"
        name="${name/.git/}" #i didn't find how to make it in one command
        destination="vendor/${name}"
        cd $destination
        git pull --depth=1
    done

    cd ~/.emacs.d/
}

case "$1" in
    "reinstall") reinstall ;;
    "update") update ;;
    "recompile") recompile ;;
    *) default ;;
esac
